language: php

php:
- 7.0

sudo: required

services:
- docker

before_install:
- docker pull edamov/pushok:7.0

script:
- docker run --name=php7.0 -e TRAVIS=true -e TRAVIS_JOB_ID="${TRAVIS_JOB_ID}" -d -v /home/travis/build/edamov/telegraph-api-php-client:/home/telegraph-api-php-client edamov/pushok:7.0 tail -f /dev/null
- docker exec -t php7.0 /bin/sh -c "cd /home/telegraph-api-php-client && php /composer.phar update ${COMPOSER_FLAGS} --no-interaction --prefer-dist && /home/telegraph-api-php-client/vendor/bin/phpunit --coverage-clover /home/telegraph-api-php-client/build/logs/clover.xml && php /home/telegraph-api-php-client/vendor/bin/coveralls -v"
